apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: complex-pipeline
spec:
  params:
    - name: gitrepositoryurl
      type: string
      description: Git Repo
    - name: gitrevision
      type: string
      description: Git Repo
      default: master
  workspaces:
    - name: maven-settings
    - name: shared-workspace
    - name: shared-repo
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.gitrepositoryurl)
        - name: revision
          value: $(params.gitrevision)
        - name: deleteExisting
          value: "true"
        - name: depth
          value: "0"
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: build
      taskRef:
        name: maven
      params:
        - name: GOALS
          value:
            - clean
            - compile
            - package
        - name: MAVEN_MIRROR_URL
          value: http://my-nexusrepo-sonatype-nexus-cicd-tools.apps.mw.consulting-rh-br.com/repository/maven-public/
      runAfter:
        - git-clone
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
        - name: local-repo
          workspace: shared-repo
    - name: tests
      taskRef:
        name: maven
      params:
        - name: GOALS
          value:
            - test
        - name: MAVEN_MIRROR_URL
          value: http://my-nexusrepo-sonatype-nexus-cicd-tools.apps.mw.consulting-rh-br.com/repository/maven-public/
      runAfter:
        - build
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
        - name: local-repo
          workspace: shared-repo
    - name: static-code-analysis
      taskRef:
        name: maven
      params:
        - name: GOALS
          value:
            - 'sonar:sonar'
            - -Dsonar.host.url=http://my-sonarqube-cicd-tools.apps.mw.consulting-rh-br.com
        - name: MAVEN_MIRROR_URL
          value: http://my-nexusrepo-sonatype-nexus-cicd-tools.apps.mw.consulting-rh-br.com/repository/maven-public/
      runAfter:
        - build
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
        - name: local-repo
          workspace: shared-repo
    - name: validate-quality-gate
      taskRef:
        name: validate-quality-gate
      params:
        - name: SONAR_URL
          value: http://my-sonarqube-cicd-tools.apps.mw.consulting-rh-br.com
      runAfter:
        - static-code-analysis
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-package
      taskRef:
        name: tar-quarkus
      runAfter:
        - tests
        - validate-quality-gate
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-image
      taskRef:
        name: openshift-client
      params:
        - name: ARGS
          value:
            - start-build
            - basic-quarkus-app
            - --from-archive=/workspace/source/target/package.tar
            - --follow
            - --wait
      runAfter:
        - build-package
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: setup-app
      taskRef:
        name: openshift-client
      params:
        - name: ARGS
          value:
            - apply
            - -f 
            - /workspace/source/deployment
      runAfter:
        - build-image
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: deploy
      taskRef:
        name: openshift-client
      params:
        - name: ARGS
          value:
            - rollout
            - latest 
            - basic-quarkus-app
      runAfter:
        - setup-app
      workspaces:
        - name: source
          workspace: shared-workspace
