#apiVersion: v1
#kind: Secret
#metadata:
#  name: 6340056--mohashi-1-pull-secret
#data:
#  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJyZWdpc3RyeS5yZWRoYXQuaW8iOiB7CiAgICAgICAgICAgICJhdXRoIjogIk5qTTBNREExTm53dGJXOW9ZWE5vYVMweE9tVjVTbWhpUjJOcFQybEtVMVY2VlhoTmFVbzVMbVY1U25wa1YwbHBUMmxKTTA1RVZYZE5WRTVxVGtSbk1VMUhXVEJhUkdjd1dWUlplRTlYV1RST01sWnNXbFJaZDFwdFJYaFBRMG81TGxOU2QxTnNXWFpRU1c1UWFYaGlNbnB2VTBwWmFra3dMV2RzZVhOMmEzWkJkemx3U2tkaVVIWlFOa3BzVFRKT1ZXNDNWVUU1ZWpaVWJXazVla2Q2Wlc1amMxUllWMnN6ZERVd2IxOWFVblJEUlZWWWFreFVUbk01ZDNkZlpXSnNXa0o0UVhGWlZGRnpXVEkzUkZaWGVVczNZVGRvTkVWeWVFSXhabTU1YVhnM1NYcEJWa2RDTUdOdE5qRlRkMHhrWm5oSFduSmpPVGx5Tm14dFdWTk9TVWRtTVVGUlYzVlFlRzh0YzNaTE1GSnhiRGN0VGpSMU5raHFSSEZCUzNRd1EweGhZV2hTUkZWYWVUSkxablJ5UmxJMGNHVkVjM2czYUVSYVNVb3ROMGRsUTE5d05UQm9NbkF3TmpVME9Wb3dZelJFVjJ0aU5sRTFNVGQ1U21NeU1IQmlSbkY2WjFGWVlqTjBNVnB3VEVwc2NVTkdVa0pSYjBaVVdYcHVhMUpDZVdOamNESlVXbU51VnpNelkySndUek40UnpKUmMwdG9aRWRZVkc5NFlVZEVUSFpHWm1aNU5HTkhiWEZZU25oYVZVVk5Oa2xvVUY5T2JHWmFWRUZ0WDNwbmR6YzNSa2hLWTI1NmMyMVVVVkF4U1dST1pYbFdkMHBPVmpNd2EyRkJlRVZ1WlhSdlpVSjJOVE5aY1VKbGRYb3RTVWt3WkhRM056RnRRa2RoZVdGRFJEbFVTVnA0UW10U1NpMXlORjh4TFhFMU9ERXlNVVJaZEdOWWNqaE5aV05XVTNKRFZUUldVbkZ2ZGtacFQxcDNWV2hJTUVOMVNWWTViemhQU1ZoelpEbHVXbEJPWlRCMWVrUjJjelZsVTI0d1Z5MHdjVjlzVEY5TWNuaG9hM0JrV1VaalRURnFUazF6YTJGaGVYWlhYM2RZV1ZSMmNIaHNPRXhoUzNCQlFsZENXbUpxUm1ZeWVtaHRSRlExV0VwTGRWQmllWEk1U1RCb01FVmFTbmwwY1RWVlh6UmZaREJHZFVGSmJESTVNbDlxTlRsR1ZYQXphWFZSVmpOaWRYQllTbFpUYVZwNFpqTk9PR2RvT1VzMmRIZGpXV2xXVDJoNVdFOVVTR2xqU2xocGFYSkZaV1pDZWxwMVkyZHZZWFJYTlhSUFowVXhNelJEVGs5RU1rMTZlbTVVUVhwWWRVTjVRbEZCIgogICAgICAgIH0sCiAgICAgICAgInJlZ2lzdHJ5LmNvbm5lY3QucmVkaGF0LmNvbSI6IHsKICAgICAgICAgICAgImF1dGgiOiAiTmpNME1EQTFObnd0Ylc5b1lYTm9hUzB4T21WNVNtaGlSMk5wVDJsS1UxVjZWWGhOYVVvNUxtVjVTbnBrVjBscFQybEpNMDVFVlhkTlZFNXFUa1JuTVUxSFdUQmFSR2N3V1ZSWmVFOVhXVFJPTWxac1dsUlpkMXB0UlhoUFEwbzVMbE5TZDFOc1dYWlFTVzVRYVhoaU1ucHZVMHBaYWtrd0xXZHNlWE4yYTNaQmR6bHdTa2RpVUhaUU5rcHNUVEpPVlc0M1ZVRTVlalpVYldrNWVrZDZaVzVqYzFSWVYyc3pkRFV3YjE5YVVuUkRSVlZZYWt4VVRuTTVkM2RmWldKc1drSjRRWEZaVkZGeldUSTNSRlpYZVVzM1lUZG9ORVZ5ZUVJeFptNTVhWGczU1hwQlZrZENNR050TmpGVGQweGtabmhIV25Kak9UbHlObXh0V1ZOT1NVZG1NVUZSVjNWUWVHOHRjM1pMTUZKeGJEY3RUalIxTmtocVJIRkJTM1F3UTB4aFlXaFNSRlZhZVRKTFpuUnlSbEkwY0dWRWMzZzNhRVJhU1VvdE4wZGxRMTl3TlRCb01uQXdOalUwT1Zvd1l6UkVWMnRpTmxFMU1UZDVTbU15TUhCaVJuRjZaMUZZWWpOME1WcHdURXBzY1VOR1VrSlJiMFpVV1hwdWExSkNlV05qY0RKVVdtTnVWek16WTJKd1R6TjRSekpSYzB0b1pFZFlWRzk0WVVkRVRIWkdabVo1TkdOSGJYRllTbmhhVlVWTk5rbG9VRjlPYkdaYVZFRnRYM3BuZHpjM1JraEtZMjU2YzIxVVVWQXhTV1JPWlhsV2QwcE9Wak13YTJGQmVFVnVaWFJ2WlVKMk5UTlpjVUpsZFhvdFNVa3daSFEzTnpGdFFrZGhlV0ZEUkRsVVNWcDRRbXRTU2kxeU5GOHhMWEUxT0RFeU1VUlpkR05ZY2poTlpXTldVM0pEVlRSV1VuRnZka1pwVDFwM1ZXaElNRU4xU1ZZNWJ6aFBTVmh6WkRsdVdsQk9aVEIxZWtSMmN6VmxVMjR3Vnkwd2NWOXNURjlNY25ob2EzQmtXVVpqVFRGcVRrMXphMkZoZVhaWFgzZFlXVlIyY0hoc09FeGhTM0JCUWxkQ1dtSnFSbVl5ZW1odFJGUTFXRXBMZFZCaWVYSTVTVEJvTUVWYVNubDBjVFZWWHpSZlpEQkdkVUZKYkRJNU1sOXFOVGxHVlhBemFYVlJWak5pZFhCWVNsWlRhVnA0WmpOT09HZG9PVXMyZEhkaldXbFdUMmg1V0U5VVNHbGpTbGhwYVhKRlpXWkNlbHAxWTJkdllYUlhOWFJQWjBVeE16UkRUazlFTWsxNmVtNVVRWHBZZFVONVFsRkIiCiAgICAgICAgfQogICAgfQp9
#type: kubernetes.io/dockerconfigjson
#---
#apiVersion: v1
#imagePullSecrets:
#- name: 6340056--mohashi-1-pull-secret
#kind: ServiceAccount
#metadata:
#  name: builder
#  namespace: cicd-tools
#---
#apiVersion: v1
#imagePullSecrets:
#- name: 6340056--mohashi-1-pull-secret
#kind: ServiceAccount
#metadata:
#  name: default
#  namespace: cicd-tools
#---
#apiVersion: v1
#imagePullSecrets:
#- name: 6340056--mohashi-1-pull-secret
#kind: ServiceAccount
#metadata:
#  name: deployer
#  namespace: cicd-tools
#---
apiVersion: sonatype.com/v1alpha1
kind: NexusRepo
metadata:
  name: my-nexusrepo
  namespace: cicd-tools
spec:
  config:
    data: null
    enabled: false
    mountPath: /sonatype-nexus-conf
  deployment:
    additionalContainers: null
    additionalVolumeMounts: null
    additionalVolumes: null
    annotations: {}
    initContainers: null
    postStart:
      command: null
    preStart:
      command: null
    terminationGracePeriodSeconds: 120
  deploymentStrategy: {}
  ingress:
    annotations: {}
    enabled: false
    path: /
    rules: null
    tls:
      enabled: true
      secretName: nexus-tls
  nexus:
    dockerPort: 5003
    env:
      - name: install4jAddVmParams
        value: >-
          -Xms1200M -Xmx1200M -XX:MaxDirectMemorySize=2G
          -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
      - name: NEXUS_SECURITY_RANDOMPASSWORD
        value: 'false'
    hostAliases: []
    imageName: 'registry.connect.redhat.com/sonatype/nexus-repository-manager:3.23.0-ubi-1'
    imagePullPolicy: IfNotPresent
    imagePullSecret: ''
    livenessProbe:
      failureThreshold: 6
      initialDelaySeconds: 30
      path: /
      periodSeconds: 30
    nexusPort: 8081
    podAnnotations: {}
    readinessProbe:
      failureThreshold: 6
      initialDelaySeconds: 30
      path: /
      periodSeconds: 30
    resources: {}
    securityContext:
      fsGroup: 1000630000
    service:
      type: ClusterIP
  nexusProxyRoute:
    annotations: null
    enabled: false
    labels: null
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    storageSize: 8Gi
  replicaCount: 1
  route:
    annotations: null
    enabled: false
    labels: null
    name: my-nexus
    portName: my-nexus
  secret:
    data: null
    enabled: false
    mountPath: /etc/secret-volume
    readOnly: true
  service:
    annotations: {}
    enabled: false
    labels: {}
    ports:
      - name: http
        port: 8081
        targetPort: 8081
  statefulset:
    enabled: false
  tolerations: []
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonatype-nexus
  name: my-nexus
  namespace: cicd-tools
spec:
  ports:
  - name: port-1
    port: 5003
    protocol: TCP
    targetPort: 5003
  - name: port-2
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: sonatype-nexus
    release: my-nexusrepo
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: sonatype-nexus
  name: my-nexus
  namespace: cicd-tools
spec:
  port:
    targetPort: 8081
  to:
    kind: Service
    name: my-nexus
    weight: 100
  wildcardPolicy: None
