apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  resources:
  - name: app-git
    type: git  
  tasks:
    - name: fetch-repository
      taskRef:
        name: dir-structure
      resources:
        inputs:
        - name: source
          resource: app-git
      params:
      - name: subdirectory
        value: .
    - name: print-readme
      taskRef:
        name: cat-readme
      runAfter:
      - fetch-repository # required to ensure clone occurs before reading
      resources:
        inputs:
        - name: source
          resource: app-git
      params:
      - name: subdirectory
        value: .
  workspaces:
  - name: shared-workspace
    description: The folder where we write the script to
