apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: results-task
spec:
  params:
    - name: message
      type: string
      default: "Default"
  results:
    - name: size-python-script
      description: The size of the python script
  steps:
    - name: create-python-script
      image: centos
      script: |
        #!/bin/sh
        cat > $(workspaces.script-folder.path)/main.py << EOF
        import sys

        print(f'Message: {sys.argv[1:]}')
        EOF
        du -hs0 $(workspaces.script-folder.path)/main.py >> /tekton/results/size-python-script
    - name: execute-python-script
      image: python
      command:
        - python
      args: 
        - $(workspaces.script-folder.path)/main.py
        - $(params.message)
  workspaces:
  - name: script-folder
    description: The folder where we write the script to
    mountPath: /workspace