apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nxrm-operator-certified
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: nxrm-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: nxrm-operator-certified.v3.23.0-1