apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: complex-pipeline-listener-interceptor
spec:
  serviceAccountName: pipeline
  triggers:
    - name: complex-trigger
      bindings:
        - name: complex-pipeline-binding
      template:
        name: complex-pipeline-template